apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentinel-vault-inventory-a
  labels:
    app: sentinel-vault-inventory-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentinel-vault-inventory-a
  template:
    metadata:
      labels:
        app: sentinel-vault-inventory-a
    spec:
      containers:
        - name: app
          image: acrcloudsec.azurecr.io/sentinel-vault-inventory:patron-a
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SECRET_SOURCE
              value: "env"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password-secret
                  key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: sentinel-vault-inventory-svc-a
spec:
  selector:
    app: sentinel-vault-inventory-a
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
