apiVersion: v1
kind: ServiceAccount
metadata:
  name: sentinel-vault-sa
  annotations:
    azure.workload.identity/client-id: "2f9a4246-3008-497c-9639-3297079a6bc1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentinel-vault-inventory-b
  labels:
    app: sentinel-vault-inventory-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentinel-vault-inventory-b
  template:
    metadata:
      labels:
        app: sentinel-vault-inventory-b
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: sentinel-vault-sa
      containers:
        - name: app
          image: acrcloudsec.azurecr.io/sentinel-vault-inventory:patron-b
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SECRET_SOURCE
              value: "vault"
            - name: KEY_VAULT_URL
              value: "https://kv-cloud-sec-demo.vault.azure.net/"
            - name: KEY_VAULT_SECRET_NAME
              value: "db-password"
---
apiVersion: v1
kind: Service
metadata:
  name: sentinel-vault-inventory-svc-b
spec:
  selector:
    app: sentinel-vault-inventory-b
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
