name: pipeline-patron-a
on:
  workflow_dispatch:
  push:
    paths:
      - "app.py"
      - "templates/**"
      - "k8s/manifest-patron-a.yml"
      - "Dockerfile"
      - "requirements.txt"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: ACR login
        run: az acr login --name acrcloudsec

      - name: Build and push image to ACR
        run: |
          docker build -t acrcloudsec.azurecr.io/sentinel-vault-inventory:patron-a .
          docker push acrcloudsec.azurecr.io/sentinel-vault-inventory:patron-a
      - name: Extract secret from Key Vault (evidencia P1 - fuga en log)
        run: |
          SECRET=$(az keyvault secret show \
            --vault-name kv-cloud-sec-demo \
            --name db-password \
            --query value -o tsv)
          echo "Valor extraido del vault: $SECRET"
          echo "DB_PASSWORD=$SECRET" >> $GITHUB_ENV
      
      - name: Set AKS context
        uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}
      
      - name: Crear K8s Secret con el valor (evidencia P2 - queda en etcd)
        run: |
          kubectl create secret generic db-password-secret \
            --from-literal=DB_PASSWORD=${{ env.DB_PASSWORD }} \
            --dry-run=client -o yaml | kubectl apply -f -
      
      - name: Deploy Patron A
        run: kubectl apply -f k8s/manifest-patron-a.yml
